spring:
  application:
    name: lovable

  datasource:
    url: jdbc:postgresql://localhost:9010/pgvector-test
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  ai:
    openai:
      api-key:
      chat:
        options:
          stream-usage: true
          model: gpt-5.4-mini
          temperature: 0.0
    ollama:
      chat:
        options:
          model: qwen3:4b
          temperature: 0.0

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: your-very-long-super-secret-jwt-secret-key

stripe:
  api:
    secret: sk_test_51RfgytFan6Z9t5aGmIRPLPPGjBResY2jdP32xCL6tcijnGfdXp1tUgb8m5WzrrgJ9ZiutKAsvCR2EithBL5KwV8Q00O3jKGv0v
  webhook:
    secret: whsec_64ac8823f5f305ff1b9612caf8d575671591048ac9bcfc1cf0d0336aeb0cd1e2

client:
  url: http://localhost:8080

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects